# Clave única de tu proyecto en SonarCloud (usualmente: tu-usuario_nombre-repo)
sonar.projectKey=ioseph06-api-restful

# Tu organización en SonarCloud (para cuentas gratuitas, suele ser tu mismo usuario de GitHub)
sonar.organization=ioseph06

# Esta es la URL de SonarCloud
sonar.host.url=https://sonarcloud.io

# Directorio donde está el código fuente
sonar.sources=.

# Excluir archivos que no queremos analizar (como migraciones generadas o configuraciones)
sonar.exclusions=**/Migrations/**, **/bin/**, **/obj/**, **/*.csproj

# Opcional: Dónde están tus pruebas para que SonarCloud mida la cobertura
sonar.tests=MiPrimeraApi.Tests
sonar.test.inclusions=**/*.Tests.cs